name: CI Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ master ]
  workflow_dispatch:
permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
  # MAUI Windows Build
  build-windows:
    runs-on: windows-2022
    name: Windows Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore ServiceBusTool.Blazor/ServiceBusTool.Blazor.csproj

      - name: Create PFX certificate
        id: create-pfx
        shell: pwsh
        env:
          PFX_CONTENT: ${{ secrets.SIGNINGCERTIFICATE }}
          GITHUB_OUTPUT: variables.GITHUB_OUTPUT
        run: |
          $pfxPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "ServiceBusTool.Blazor";
          $pfxPath = Join-Path -Path $pfxPath -ChildPath "cert.pfx";
          $encodedBytes = [System.Convert]::FromBase64String($env:PFX_CONTENT);
          Set-Content $pfxPath -Value $encodedBytes -AsByteStream;
          Write-Output "::set-output name=PFX_PATH::$pfxPath";

      - name: Build MAUI Windows
        run: dotnet publish ServiceBusTool.Blazor/ServiceBusTool.Blazor.csproj -c Release -f net6.0-windows10.0.19041.0 --no-restore

      - name: Delete PFX certificate
        shell: pwsh
        env:
          PFX_PATH: ${{ steps.create-pfx.outputs.PFX_PATH }}
        run: |
          Remove-Item -Path $env:PFX_PATH;

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: service-bus-tool-windows
          path: ServiceBusTool.Blazor/bin/Release/net6.0-windows10.0.19041.0/win10-x64/AppPackages/ServiceBusTool.Blazor*/ServiceBusTool.Blazor*.msix
